import turtle
super_h = turtle.Turtle()
turtle.Screen().bgcolor('blue')
turtle.title("Super Homem")


def curve(value):
    for i in range(value):
        super_h.right(1)
        super_h.forward(1)


super_h.penup()
super_h.setposition(0, 43)
super_h.pendown()
super_h.begin_fill()
super_h.pencolor('black')
super_h.fillcolor('maroon')
super_h.pensize(3)
super_h.forward(81.5)
super_h.right(49.4)
super_h.forward(58)
super_h.right(81.42)
super_h.forward(182)
super_h.right(98.36)
super_h.forward(182)
super_h.right(81.42)
super_h.forward(58)
super_h.right(49.4)
super_h.forward(81.5)
super_h.end_fill()
super_h.penup()

super_h.setposition(38, 32)
super_h.pendown()
super_h.begin_fill()
super_h.fillcolor('gold')
super_h.forward(13)
super_h.right(120)
super_h.forward(13)
super_h.right(120)
super_h.forward(13)
super_h.end_fill()
super_h.penup()

super_h.setposition(81.5, 25)
super_h.pendown()
super_h.begin_fill()
super_h.right(210)
super_h.forward(25)
super_h.right(90)
super_h.forward(38)
super_h.right(45)
super_h.circle(82, 90)
super_h.left(90)
super_h.circle(82, 60)
curve(61)
super_h.left(90)
super_h.forward(57)
super_h.left(90)
super_h.forward(32)
super_h.end_fill()
super_h.penup()
super_h.home()

super_h.setposition(-69, -38)
super_h.pendown()
super_h.begin_fill()
curve(20)
super_h.forward(33)
super_h.left(10)
super_h.circle(82, 20)
curve(30)
super_h.forward(10)
super_h.right(110)
curve(40)
super_h.right(10)
super_h.circle(50, 10)
curve(45)
super_h.right(5)
super_h.forward(45)
super_h.end_fill()
super_h.penup()
super_h.home()

super_h.setposition(20, -100)
super_h.pendown()
super_h.begin_fill()
super_h.right(135)
super_h.forward(27)
super_h.right(90)
super_h.forward(27)
super_h.right(135)
super_h.forward(38.18)
super_h.end_fill()
super_h.penup()
super_h.home()

super_h.setposition(-57, 32)
super_h.pendown()
super_h.begin_fill()
super_h.right(180)
super_h.forward(18)
super_h.left(45)
super_h.forward(44)
super_h.left(80)
super_h.forward(15)
super_h.left(130)
curve(40)
super_h.forward(20)
super_h.end_fill()

super_h.hideturtle()
turtle.exitonclick()